import type { ExerciseLibraryItem } from "@/types";
import { slugifyExerciseName } from "@/lib/exercise-utils";

const createdAt = "2026-04-18T00:00:00.000Z";

type SeedExercise = Omit<ExerciseLibraryItem, "id" | "slug" | "createdAt" | "updatedAt" | "isActive" | "isGlobal" | "createdBy"> & {
  id: string;
};

const seedExercises: SeedExercise[] = [
  {
    id: "ex-lib-001",
    name: "Agachamento livre",
    category: "Musculação",
    muscleCategory: "Quadríceps",
    muscleGroupPrimary: "Quadríceps",
    muscleGroupsSecondary: ["Glúteo máximo", "Core"],
    movementType: "Agachar",
    bodyRegion: "Membros inferiores",
    equipment: "Barra",
    difficultyLevel: "Intermediário",
    exerciseType: "Força",
    description: "Exercício base para desenvolvimento de força e controle de membros inferiores.",
    executionInstructions: "Posicione a barra com estabilidade, desça com o quadril para trás e suba empurrando o chão.",
    breathingTips: "Inspire antes da descida e solte o ar ao passar da fase mais difícil.",
    postureTips: "Mantenha o tronco firme, joelhos acompanhando a ponta dos pés e pés bem apoiados.",
    contraindications: "Evite em crises agudas de lombalgia sem liberação profissional.",
    commonMistakes: "Perder a curvatura neutra da coluna e projetar os joelhos sem controle.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-002",
    name: "Leg press 45°",
    category: "Musculação",
    muscleCategory: "Quadríceps",
    muscleGroupPrimary: "Quadríceps",
    muscleGroupsSecondary: ["Glúteo máximo", "Posterior de coxa"],
    movementType: "Empurrar",
    bodyRegion: "Membros inferiores",
    equipment: "Máquina",
    difficultyLevel: "Iniciante",
    exerciseType: "Hipertrofia",
    description: "Exercício guiado para trabalho de pernas com foco em estabilidade.",
    executionInstructions: "Desça o trenó até uma amplitude segura e empurre sem estender totalmente os joelhos.",
    breathingTips: "Inspire na descida e expire ao empurrar a plataforma.",
    postureTips: "Mantenha a lombar apoiada e os pés alinhados na largura confortável.",
    contraindications: "Ajuste a amplitude em casos de desconforto no quadril ou joelhos.",
    commonMistakes: "Tirar o quadril do encosto e travar os joelhos ao final.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-003",
    name: "Levantamento terra romeno",
    category: "Musculação",
    muscleCategory: "Posterior de coxa",
    muscleGroupPrimary: "Posterior de coxa",
    muscleGroupsSecondary: ["Glúteo máximo", "Eretores da espinha"],
    movementType: "Levantar",
    bodyRegion: "Membros inferiores",
    equipment: "Barra",
    difficultyLevel: "Intermediário",
    exerciseType: "Força",
    description: "Movimento dominante de quadril para cadeia posterior.",
    executionInstructions: "Flexione levemente os joelhos, projete o quadril para trás e retorne com controle.",
    breathingTips: "Inspire antes da descida e expire ao retornar à posição inicial.",
    postureTips: "Mantenha a barra próxima do corpo e a coluna neutra durante todo o percurso.",
    contraindications: "Evite em dor lombar aguda sem adaptação do movimento.",
    commonMistakes: "Arredondar as costas e transformar o movimento em agachamento.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-004",
    name: "Supino reto com barra",
    category: "Musculação",
    muscleCategory: "Peito",
    muscleGroupPrimary: "Peitoral maior",
    muscleGroupsSecondary: ["Deltoide anterior", "Tríceps braquial"],
    movementType: "Empurrar",
    bodyRegion: "Membros superiores",
    equipment: "Barra",
    difficultyLevel: "Intermediário",
    exerciseType: "Força",
    description: "Exercício clássico para peitoral com alta sobrecarga mecânica.",
    executionInstructions: "Desça a barra até a linha média do peito e empurre mantendo punhos alinhados.",
    breathingTips: "Inspire na descida e solte o ar na subida.",
    postureTips: "Escápulas apoiadas, pés firmes no chão e leve arco natural do tronco.",
    contraindications: "Ajuste a pegada em casos de dor no ombro.",
    commonMistakes: "Perder a estabilidade escapular e quicar a barra no peito.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-005",
    name: "Supino inclinado com halteres",
    category: "Musculação",
    muscleCategory: "Peito",
    muscleGroupPrimary: "Peitoral maior",
    muscleGroupsSecondary: ["Deltoide anterior", "Tríceps braquial"],
    movementType: "Empurrar",
    bodyRegion: "Membros superiores",
    equipment: "Halteres",
    difficultyLevel: "Intermediário",
    exerciseType: "Hipertrofia",
    description: "Variação inclinada para maior ênfase na porção clavicular do peitoral.",
    executionInstructions: "Desça os halteres com controle e suba sem perder a linha dos punhos.",
    breathingTips: "Inspire na descida e expire na subida.",
    postureTips: "Mantenha o banco ajustado e as escápulas bem apoiadas.",
    contraindications: "Reduza a inclinação se houver desconforto anterior no ombro.",
    commonMistakes: "Bater os halteres no topo e abrir demais os cotovelos.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-006",
    name: "Remada curvada com barra",
    category: "Musculação",
    muscleCategory: "Costas",
    muscleGroupPrimary: "Latíssimo do dorso",
    muscleGroupsSecondary: ["Romboides", "Trapézio", "Bíceps braquial"],
    movementType: "Puxar",
    bodyRegion: "Membros superiores",
    equipment: "Barra",
    difficultyLevel: "Intermediário",
    exerciseType: "Força",
    description: "Remada livre para desenvolvimento de dorsais e estabilização do tronco.",
    executionInstructions: "Incline o tronco, mantenha o abdômen ativo e puxe a barra em direção ao abdômen.",
    breathingTips: "Expire durante a puxada e inspire ao retornar.",
    postureTips: "Evite perder a posição neutra da coluna e mantenha os ombros longe das orelhas.",
    contraindications: "Requer adaptação em casos de baixa tolerância à inclinação de tronco.",
    commonMistakes: "Roubar com o quadril e puxar só com os braços.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-007",
    name: "Puxada frontal na polia",
    category: "Musculação",
    muscleCategory: "Costas",
    muscleGroupPrimary: "Latíssimo do dorso",
    muscleGroupsSecondary: ["Bíceps braquial", "Romboides"],
    movementType: "Puxar",
    bodyRegion: "Membros superiores",
    equipment: "Cabo",
    difficultyLevel: "Iniciante",
    exerciseType: "Hipertrofia",
    description: "Puxada guiada para desenvolvimento de dorsais.",
    executionInstructions: "Puxe a barra até a parte superior do peito com cotovelos apontando para baixo.",
    breathingTips: "Expire ao puxar e inspire na volta controlada.",
    postureTips: "Mantenha o tronco estável, sem jogar o corpo para trás.",
    contraindications: "Ajuste a amplitude em caso de dor no ombro.",
    commonMistakes: "Puxar atrás da nuca e compensar com balanço excessivo.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-008",
    name: "Desenvolvimento com halteres",
    category: "Musculação",
    muscleCategory: "Ombros",
    muscleGroupPrimary: "Deltoide anterior",
    muscleGroupsSecondary: ["Deltoide lateral", "Tríceps braquial"],
    movementType: "Empurrar",
    bodyRegion: "Membros superiores",
    equipment: "Halteres",
    difficultyLevel: "Intermediário",
    exerciseType: "Hipertrofia",
    description: "Movimento vertical para fortalecimento dos ombros.",
    executionInstructions: "Empurre os halteres acima da cabeça sem perder a estabilidade do tronco.",
    breathingTips: "Expire ao subir e inspire na descida.",
    postureTips: "Costelas encaixadas e glúteos ativos para evitar compensação lombar.",
    contraindications: "Modere a amplitude em caso de limitação articular do ombro.",
    commonMistakes: "Arquear demais a lombar e perder controle dos punhos.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-009",
    name: "Elevação lateral",
    category: "Musculação",
    muscleCategory: "Ombros",
    muscleGroupPrimary: "Deltoide lateral",
    muscleGroupsSecondary: ["Trapézio"],
    movementType: "Empurrar",
    bodyRegion: "Membros superiores",
    equipment: "Halteres",
    difficultyLevel: "Iniciante",
    exerciseType: "Hipertrofia",
    description: "Exercício de isolamento para ombros.",
    executionInstructions: "Eleve os braços lateralmente até a linha dos ombros com cotovelos levemente flexionados.",
    breathingTips: "Expire ao elevar e inspire ao descer.",
    postureTips: "Mantenha o pescoço relaxado e o tronco sem balanço.",
    contraindications: "Ajuste o arco do movimento em casos de impacto no ombro.",
    commonMistakes: "Subir os ombros e usar impulso do tronco.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-010",
    name: "Rosca direta com barra",
    category: "Musculação",
    muscleCategory: "Bíceps",
    muscleGroupPrimary: "Bíceps braquial",
    muscleGroupsSecondary: ["Braquial", "Antebraços"],
    movementType: "Puxar",
    bodyRegion: "Membros superiores",
    equipment: "Barra",
    difficultyLevel: "Iniciante",
    exerciseType: "Hipertrofia",
    description: "Flexão de cotovelos para trabalho de bíceps.",
    executionInstructions: "Suba a barra sem projetar os ombros e retorne com controle.",
    breathingTips: "Expire na subida e inspire na descida.",
    postureTips: "Cotovelos próximos ao corpo e tronco estável.",
    contraindications: "Ajuste a pegada se houver desconforto no punho.",
    commonMistakes: "Roubar com balanço e elevar os cotovelos.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-011",
    name: "Tríceps na polia com corda",
    category: "Musculação",
    muscleCategory: "Tríceps",
    muscleGroupPrimary: "Tríceps braquial",
    muscleGroupsSecondary: ["Deltoide posterior"],
    movementType: "Empurrar",
    bodyRegion: "Membros superiores",
    equipment: "Cabo",
    difficultyLevel: "Iniciante",
    exerciseType: "Hipertrofia",
    description: "Extensão de cotovelos guiada para tríceps.",
    executionInstructions: "Empurre a corda para baixo e finalize abrindo levemente as mãos no fim do movimento.",
    breathingTips: "Expire ao estender os cotovelos e inspire ao retornar.",
    postureTips: "Cotovelos fixos ao lado do tronco e peito aberto.",
    contraindications: "Evite cargas altas em irritações recentes no cotovelo.",
    commonMistakes: "Mover os ombros para ajudar e encurtar demais a amplitude.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-012",
    name: "Hip thrust com barra",
    category: "Musculação",
    muscleCategory: "Glúteos",
    muscleGroupPrimary: "Glúteo máximo",
    muscleGroupsSecondary: ["Posterior de coxa", "Core"],
    movementType: "Levantar",
    bodyRegion: "Membros inferiores",
    equipment: "Barra",
    difficultyLevel: "Intermediário",
    exerciseType: "Hipertrofia",
    description: "Exercício dominante de quadril com foco em glúteos.",
    executionInstructions: "Eleve o quadril até alinhar joelhos, quadril e ombros, controlando a descida.",
    breathingTips: "Expire no topo e inspire na descida.",
    postureTips: "Queixo levemente recolhido e pés posicionados para manter a canela próxima da vertical.",
    contraindications: "Ajuste o apoio se houver desconforto na lombar.",
    commonMistakes: "Hiperestender a lombar e posicionar os pés muito à frente.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-013",
    name: "Panturrilha em pé na máquina",
    category: "Musculação",
    muscleCategory: "Panturrilhas",
    muscleGroupPrimary: "Panturrilhas",
    muscleGroupsSecondary: [],
    movementType: "Empurrar",
    bodyRegion: "Membros inferiores",
    equipment: "Máquina",
    difficultyLevel: "Iniciante",
    exerciseType: "Resistência",
    description: "Movimento guiado para flexão plantar.",
    executionInstructions: "Suba na ponta dos pés, segure um instante e desça controlando a amplitude.",
    breathingTips: "Expire ao subir e inspire ao descer.",
    postureTips: "Evite balanço do tronco e mantenha o movimento completo.",
    contraindications: "Modere a amplitude em tendinopatias do calcâneo.",
    commonMistakes: "Fazer repetições muito curtas e rápidas demais.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-014",
    name: "Prancha frontal",
    category: "Musculação",
    muscleCategory: "Abdômen",
    muscleGroupPrimary: "Core",
    muscleGroupsSecondary: ["Reto abdominal", "Oblíquos"],
    movementType: "Isométrico",
    bodyRegion: "Tronco",
    equipment: "Peso corporal",
    difficultyLevel: "Iniciante",
    exerciseType: "Ativação",
    description: "Exercício isométrico para estabilidade do tronco.",
    executionInstructions: "Apoie antebraços e pontas dos pés, mantendo o corpo alinhado do ombro ao tornozelo.",
    breathingTips: "Respire continuamente sem prender o ar.",
    postureTips: "Ative glúteos e abdômen para evitar queda do quadril.",
    contraindications: "Adapte em casos de dor no ombro ou punhos.",
    commonMistakes: "Elevar demais o quadril ou deixar a lombar cair.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-015",
    name: "Abdominal dead bug",
    category: "Musculação",
    muscleCategory: "Abdômen",
    muscleGroupPrimary: "Core",
    muscleGroupsSecondary: ["Reto abdominal", "Flexores do quadril"],
    movementType: "Estabilizar",
    bodyRegion: "Tronco",
    equipment: "Peso corporal",
    difficultyLevel: "Iniciante",
    exerciseType: "Ativação",
    description: "Padrão anti-extensão para estabilidade central.",
    executionInstructions: "Deitado, estenda braço e perna opostos sem perder o contato lombar com o chão.",
    breathingTips: "Expire ao afastar os membros e inspire ao retornar.",
    postureTips: "Mantenha costelas encaixadas e lombar estável.",
    contraindications: "Reduza a amplitude se houver desconforto lombar.",
    commonMistakes: "Arquear a lombar ao afastar braços e pernas.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-016",
    name: "Farmer walk com halteres",
    category: "Musculação",
    muscleCategory: "Corpo inteiro",
    muscleGroupPrimary: "Corpo inteiro",
    muscleGroupsSecondary: ["Trapézio", "Core", "Antebraços"],
    movementType: "Locomover",
    bodyRegion: "Corpo inteiro",
    equipment: "Halteres",
    difficultyLevel: "Intermediário",
    exerciseType: "Condicionamento",
    description: "Caminhada carregada para força de pegada e estabilidade global.",
    executionInstructions: "Caminhe com passadas curtas e postura alta segurando os halteres ao lado do corpo.",
    breathingTips: "Respire de forma contínua durante o deslocamento.",
    postureTips: "Ombros para baixo, abdômen ativo e olhar à frente.",
    contraindications: "Ajuste a carga em casos de dor lombar ou limitação de pegada.",
    commonMistakes: "Inclinar o tronco e caminhar com passos descontrolados.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-017",
    name: "Mobilidade torácica em quatro apoios",
    category: "Mobilidade",
    muscleCategory: "Mobilidade",
    muscleGroupPrimary: "Mobilidade",
    muscleGroupsSecondary: ["Trapézio", "Romboides"],
    movementType: "Mobilidade",
    bodyRegion: "Tronco",
    equipment: "Peso corporal",
    difficultyLevel: "Iniciante",
    exerciseType: "Mobilidade",
    description: "Melhora a rotação torácica e a consciência de tronco.",
    executionInstructions: "Em quatro apoios, leve uma mão à cabeça e gire o tronco abrindo o cotovelo para cima.",
    breathingTips: "Expire durante a rotação e inspire ao retornar.",
    postureTips: "Mantenha o quadril estável e a mão de apoio bem ativa.",
    contraindications: "Reduza a amplitude em dor aguda na coluna.",
    commonMistakes: "Compensar o movimento com rotação excessiva do quadril.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-018",
    name: "Mobilidade de tornozelo na parede",
    category: "Mobilidade",
    muscleCategory: "Mobilidade",
    muscleGroupPrimary: "Mobilidade",
    muscleGroupsSecondary: ["Panturrilhas", "Tibial anterior"],
    movementType: "Mobilidade",
    bodyRegion: "Membros inferiores",
    equipment: "Sem equipamento",
    difficultyLevel: "Iniciante",
    exerciseType: "Mobilidade",
    description: "Exercício para ganho de dorsiflexão de tornozelo.",
    executionInstructions: "Leve o joelho em direção à parede sem tirar o calcanhar do chão.",
    breathingTips: "Respire normalmente e mantenha ritmo controlado.",
    postureTips: "Evite colapsar o arco do pé durante a projeção do joelho.",
    contraindications: "Respeite desconfortos articulares e edema local.",
    commonMistakes: "Tirar o calcanhar do chão para ganhar amplitude.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-019",
    name: "90/90 de quadril",
    category: "Mobilidade",
    muscleCategory: "Mobilidade",
    muscleGroupPrimary: "Mobilidade",
    muscleGroupsSecondary: ["Glúteo médio", "Adutores"],
    movementType: "Mobilidade",
    bodyRegion: "Membros inferiores",
    equipment: "Peso corporal",
    difficultyLevel: "Intermediário",
    exerciseType: "Mobilidade",
    description: "Mobilidade de quadril com ênfase em rotações interna e externa.",
    executionInstructions: "Sente-se na posição 90/90 e alterne o tronco sobre a perna da frente com controle.",
    breathingTips: "Expire ao aproximar o tronco da perna e inspire ao retornar.",
    postureTips: "Mantenha a pelve apoiada sem colapsar o tronco.",
    contraindications: "Adapte a posição em casos de dor no joelho.",
    commonMistakes: "Forçar a amplitude sem estabilidade do quadril.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-020",
    name: "Rotação externa de ombro com elástico",
    category: "Mobilidade",
    muscleCategory: "Mobilidade",
    muscleGroupPrimary: "Manguito rotador",
    muscleGroupsSecondary: ["Deltoide posterior"],
    movementType: "Mobilidade",
    bodyRegion: "Membros superiores",
    equipment: "Elástico",
    difficultyLevel: "Iniciante",
    exerciseType: "Ativação",
    description: "Ativação do manguito rotador para estabilidade do ombro.",
    executionInstructions: "Com o cotovelo junto ao corpo, puxe o elástico para fora sem rodar o tronco.",
    breathingTips: "Expire durante a rotação e inspire na volta.",
    postureTips: "Mantenha peito aberto e escápulas estáveis.",
    contraindications: "Controle a tensão em pós-operatórios ou inflamações.",
    commonMistakes: "Afastar o cotovelo do corpo e compensar com o tronco.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-021",
    name: "Cat-camel",
    category: "Mobilidade",
    muscleCategory: "Mobilidade",
    muscleGroupPrimary: "Mobilidade",
    muscleGroupsSecondary: ["Eretores da espinha", "Core"],
    movementType: "Mobilidade",
    bodyRegion: "Tronco",
    equipment: "Peso corporal",
    difficultyLevel: "Iniciante",
    exerciseType: "Mobilidade",
    description: "Movimento fluido para mobilidade segmentar da coluna.",
    executionInstructions: "Alterne entre flexão e extensão da coluna em quatro apoios, de forma lenta.",
    breathingTips: "Expire na flexão e inspire na extensão.",
    postureTips: "Distribua o movimento pela coluna toda, sem pressa.",
    contraindications: "Evite amplitudes extremas em crises dolorosas.",
    commonMistakes: "Executar rápido demais, sem percepção segmentar.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-022",
    name: "Deep squat hold assistido",
    category: "Mobilidade",
    muscleCategory: "Mobilidade",
    muscleGroupPrimary: "Mobilidade",
    muscleGroupsSecondary: ["Quadríceps", "Glúteo máximo", "Panturrilhas"],
    movementType: "Mobilidade",
    bodyRegion: "Membros inferiores",
    equipment: "TRX",
    difficultyLevel: "Intermediário",
    exerciseType: "Mobilidade",
    description: "Permanência em agachamento profundo com apoio para ganho de amplitude.",
    executionInstructions: "Segure no apoio e mantenha o quadril baixo com a coluna o mais neutra possível.",
    breathingTips: "Respire de forma contínua enquanto sustenta a posição.",
    postureTips: "Distribua o peso no pé todo e abra o peito.",
    contraindications: "Ajuste a profundidade se houver desconforto no joelho ou quadril.",
    commonMistakes: "Deixar os calcanhares subirem e colapsar o tronco.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-023",
    name: "Passagem de bastão sobre a cabeça",
    category: "Mobilidade",
    muscleCategory: "Mobilidade",
    muscleGroupPrimary: "Mobilidade",
    muscleGroupsSecondary: ["Deltoide anterior", "Peitoral menor"],
    movementType: "Mobilidade",
    bodyRegion: "Membros superiores",
    equipment: "Barra",
    difficultyLevel: "Iniciante",
    exerciseType: "Mobilidade",
    description: "Mobilidade de ombros com barra leve ou bastão.",
    executionInstructions: "Leve o bastão da frente para trás por cima da cabeça mantendo os cotovelos estendidos.",
    breathingTips: "Respire normalmente, mantendo o ritmo controlado.",
    postureTips: "Costelas encaixadas e pescoço relaxado durante a passagem.",
    contraindications: "Reduza a amplitude em ombros muito sensíveis.",
    commonMistakes: "Compensar com hiperextensão lombar.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-024",
    name: "World's greatest stretch",
    category: "Mobilidade",
    muscleCategory: "Mobilidade",
    muscleGroupPrimary: "Mobilidade",
    muscleGroupsSecondary: ["Flexores do quadril", "Posterior de coxa", "Mobilidade"],
    movementType: "Mobilidade",
    bodyRegion: "Corpo inteiro",
    equipment: "Peso corporal",
    difficultyLevel: "Intermediário",
    exerciseType: "Mobilidade",
    description: "Sequência dinâmica para quadril, coluna torácica e cadeia posterior.",
    executionInstructions: "Avance uma perna, apoie a mão no chão e combine extensão, rotação e alongamento.",
    breathingTips: "Expire nas rotações e inspire nas transições.",
    postureTips: "Mantenha o quadril alinhado e a perna de trás ativa.",
    contraindications: "Modere a amplitude em desconfortos no quadril ou punhos.",
    commonMistakes: "Fazer transições rápidas demais, sem controle.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-025",
    name: "Alongamento de peitoral na parede",
    category: "Alongamento",
    muscleCategory: "Alongamento",
    muscleGroupPrimary: "Peitoral maior",
    muscleGroupsSecondary: ["Peitoral menor", "Deltoide anterior"],
    movementType: "Alongamento",
    bodyRegion: "Membros superiores",
    equipment: "Sem equipamento",
    difficultyLevel: "Iniciante",
    exerciseType: "Alongamento",
    description: "Alongamento estático para cadeia anterior do ombro e peitoral.",
    executionInstructions: "Apoie o braço na parede e gire o tronco suavemente para o lado oposto.",
    breathingTips: "Respire fundo e relaxe progressivamente a musculatura.",
    postureTips: "Mantenha ombros baixos e pescoço solto.",
    contraindications: "Evite intensidade alta em instabilidade de ombro.",
    commonMistakes: "Girar rápido demais e tensionar a lombar.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-026",
    name: "Alongamento de posterior sentado",
    category: "Alongamento",
    muscleCategory: "Alongamento",
    muscleGroupPrimary: "Posterior de coxa",
    muscleGroupsSecondary: ["Panturrilhas"],
    movementType: "Alongamento",
    bodyRegion: "Membros inferiores",
    equipment: "Sem equipamento",
    difficultyLevel: "Iniciante",
    exerciseType: "Alongamento",
    description: "Alongamento estático para cadeia posterior da perna.",
    executionInstructions: "Sente-se com uma perna estendida e incline o tronco à frente sem arredondar excessivamente as costas.",
    breathingTips: "Respire fundo e avance de forma gradual a cada expiração.",
    postureTips: "Cresça o tronco antes de inclinar e mantenha os ombros relaxados.",
    contraindications: "Evite forçar nervo ciático irritado.",
    commonMistakes: "Arredondar muito a lombar para alcançar o pé.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-027",
    name: "Alongamento de flexores do quadril ajoelhado",
    category: "Alongamento",
    muscleCategory: "Alongamento",
    muscleGroupPrimary: "Flexores do quadril",
    muscleGroupsSecondary: ["Quadríceps"],
    movementType: "Alongamento",
    bodyRegion: "Membros inferiores",
    equipment: "Sem equipamento",
    difficultyLevel: "Iniciante",
    exerciseType: "Alongamento",
    description: "Alongamento para região anterior do quadril.",
    executionInstructions: "Em meio-ajoelhado, projete o quadril à frente mantendo a pelve encaixada.",
    breathingTips: "Expire lentamente para aprofundar o alongamento com conforto.",
    postureTips: "Contraia levemente o glúteo da perna de trás.",
    contraindications: "Proteja o joelho com apoio quando necessário.",
    commonMistakes: "Inclinar o tronco e exagerar na extensão lombar.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-028",
    name: "Alongamento de glúteos deitado",
    category: "Alongamento",
    muscleCategory: "Alongamento",
    muscleGroupPrimary: "Glúteo máximo",
    muscleGroupsSecondary: ["Glúteo médio"],
    movementType: "Alongamento",
    bodyRegion: "Membros inferiores",
    equipment: "Sem equipamento",
    difficultyLevel: "Iniciante",
    exerciseType: "Alongamento",
    description: "Alongamento de glúteos e região posterior do quadril.",
    executionInstructions: "Cruze uma perna sobre a outra e aproxime a coxa do peito com as mãos.",
    breathingTips: "Respire fundo e relaxe o quadril a cada expiração.",
    postureTips: "Mantenha a cabeça apoiada e os ombros soltos.",
    contraindications: "Ajuste se houver desconforto no joelho cruzado.",
    commonMistakes: "Puxar demais sem manter o quadril alinhado.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-029",
    name: "Alongamento de panturrilha na parede",
    category: "Alongamento",
    muscleCategory: "Alongamento",
    muscleGroupPrimary: "Panturrilhas",
    muscleGroupsSecondary: [],
    movementType: "Alongamento",
    bodyRegion: "Membros inferiores",
    equipment: "Sem equipamento",
    difficultyLevel: "Iniciante",
    exerciseType: "Alongamento",
    description: "Alongamento estático para panturrilhas.",
    executionInstructions: "Apoie as mãos na parede, mantenha o calcanhar no chão e incline o corpo à frente.",
    breathingTips: "Respire de forma cadenciada e sem tensão excessiva.",
    postureTips: "Mantenha o pé apontado para frente e joelho estendido ou levemente flexionado conforme a variação.",
    contraindications: "Modere a intensidade em tendão de Aquiles sensível.",
    commonMistakes: "Rodar o pé para fora e tirar o calcanhar do chão.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-030",
    name: "Alongamento de tríceps acima da cabeça",
    category: "Alongamento",
    muscleCategory: "Alongamento",
    muscleGroupPrimary: "Tríceps braquial",
    muscleGroupsSecondary: ["Latíssimo do dorso"],
    movementType: "Alongamento",
    bodyRegion: "Membros superiores",
    equipment: "Sem equipamento",
    difficultyLevel: "Iniciante",
    exerciseType: "Alongamento",
    description: "Alongamento para tríceps e cadeia superior posterior.",
    executionInstructions: "Eleve um braço, dobre o cotovelo e aproxime a mão das costas auxiliando com a outra mão.",
    breathingTips: "Respire devagar, evitando elevar os ombros.",
    postureTips: "Mantenha o tronco ereto e o abdômen levemente ativo.",
    contraindications: "Reduza a amplitude em casos de limitação de ombro.",
    commonMistakes: "Projetar a cabeça à frente e arquear a lombar.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-031",
    name: "Alongamento lateral de tronco",
    category: "Alongamento",
    muscleCategory: "Alongamento",
    muscleGroupPrimary: "Oblíquos",
    muscleGroupsSecondary: ["Latíssimo do dorso"],
    movementType: "Alongamento",
    bodyRegion: "Tronco",
    equipment: "Sem equipamento",
    difficultyLevel: "Iniciante",
    exerciseType: "Alongamento",
    description: "Alongamento da lateral do tronco com foco em oblíquos e dorsais.",
    executionInstructions: "Eleve um braço acima da cabeça e incline o tronco suavemente para o lado oposto.",
    breathingTips: "Expire ao inclinar e inspire ao retornar ao centro.",
    postureTips: "Evite rodar o tronco e mantenha os quadris estáveis.",
    contraindications: "Adapte em casos de dor aguda na coluna.",
    commonMistakes: "Compensar com flexão para frente em vez de inclinação lateral.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-032",
    name: "Alongamento de adutores em borboleta",
    category: "Alongamento",
    muscleCategory: "Alongamento",
    muscleGroupPrimary: "Adutores",
    muscleGroupsSecondary: [],
    movementType: "Alongamento",
    bodyRegion: "Membros inferiores",
    equipment: "Sem equipamento",
    difficultyLevel: "Iniciante",
    exerciseType: "Alongamento",
    description: "Alongamento de adutores com sola dos pés unidas.",
    executionInstructions: "Sente-se, una as plantas dos pés e aproxime os joelhos do chão sem forçar.",
    breathingTips: "Respire profundamente e relaxe a musculatura a cada expiração.",
    postureTips: "Mantenha a coluna alta antes de aproximar o tronco dos pés.",
    contraindications: "Ajuste a posição em irritações do quadril.",
    commonMistakes: "Empurrar os joelhos agressivamente com as mãos.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-033",
    name: "Corrida na esteira",
    category: "Cardio",
    muscleCategory: "Cardiorrespiratório",
    muscleGroupPrimary: "Cardiorrespiratório",
    muscleGroupsSecondary: ["Quadríceps", "Panturrilhas", "Glúteo máximo"],
    movementType: "Cardio",
    bodyRegion: "Corpo inteiro",
    equipment: "Esteira",
    difficultyLevel: "Intermediário",
    exerciseType: "Condicionamento",
    description: "Exercício cardiovascular contínuo em esteira.",
    executionInstructions: "Ajuste ritmo e inclinação de acordo com o objetivo da sessão.",
    breathingTips: "Busque cadência respiratória estável e compatível com a intensidade.",
    postureTips: "Mantenha tronco alto, passadas naturais e braços soltos.",
    contraindications: "Controle o impacto em alunos com baixa tolerância articular.",
    commonMistakes: "Segurar nas barras e exagerar na passada.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-034",
    name: "Bicicleta ergométrica",
    category: "Cardio",
    muscleCategory: "Cardiorrespiratório",
    muscleGroupPrimary: "Cardiorrespiratório",
    muscleGroupsSecondary: ["Quadríceps", "Glúteo máximo", "Panturrilhas"],
    movementType: "Cardio",
    bodyRegion: "Membros inferiores",
    equipment: "Bicicleta",
    difficultyLevel: "Iniciante",
    exerciseType: "Condicionamento",
    description: "Cardio de baixo impacto com ajuste fino de intensidade.",
    executionInstructions: "Pedale com cadência constante e resistência compatível com a meta da aula.",
    breathingTips: "Mantenha a respiração ritmada durante o esforço.",
    postureTips: "Ajuste banco e guidão para evitar sobrecarga em joelhos e lombar.",
    contraindications: "Observe desconfortos patelofemorais e ajuste selim.",
    commonMistakes: "Pedalar com joelhos colapsando para dentro.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-035",
    name: "Pular corda",
    category: "Cardio",
    muscleCategory: "Cardiorrespiratório",
    muscleGroupPrimary: "Cardiorrespiratório",
    muscleGroupsSecondary: ["Panturrilhas", "Core"],
    movementType: "Cardio",
    bodyRegion: "Corpo inteiro",
    equipment: "Corda",
    difficultyLevel: "Intermediário",
    exerciseType: "Condicionamento",
    description: "Cardio coordenativo com alto gasto energético.",
    executionInstructions: "Realize saltos curtos e ritmados usando punhos para girar a corda.",
    breathingTips: "Estabilize a respiração em ciclos curtos e regulares.",
    postureTips: "Pouse com suavidade e mantenha os cotovelos próximos ao corpo.",
    contraindications: "Modere o impacto em alunos com baixa tolerância articular.",
    commonMistakes: "Saltar alto demais e usar os ombros para girar a corda.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-036",
    name: "Remo ergométrico",
    category: "Cardio",
    muscleCategory: "Cardiorrespiratório",
    muscleGroupPrimary: "Cardiorrespiratório",
    muscleGroupsSecondary: ["Latíssimo do dorso", "Quadríceps", "Core"],
    movementType: "Cardio",
    bodyRegion: "Corpo inteiro",
    equipment: "Máquina",
    difficultyLevel: "Intermediário",
    exerciseType: "Condicionamento",
    description: "Cardio global com coordenação entre pernas, tronco e braços.",
    executionInstructions: "Empurre com as pernas, incline o tronco e finalize com os braços em sequência fluida.",
    breathingTips: "Expire na puxada e inspire na volta.",
    postureTips: "Mantenha a coluna longa e evite arredondar excessivamente na recuperação.",
    contraindications: "Controle a amplitude em lombalgia sensível.",
    commonMistakes: "Puxar só com os braços e perder a sequência do movimento.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-037",
    name: "Escada ergométrica",
    category: "Cardio",
    muscleCategory: "Cardiorrespiratório",
    muscleGroupPrimary: "Cardiorrespiratório",
    muscleGroupsSecondary: ["Glúteo máximo", "Quadríceps", "Panturrilhas"],
    movementType: "Cardio",
    bodyRegion: "Membros inferiores",
    equipment: "Escada",
    difficultyLevel: "Intermediário",
    exerciseType: "Condicionamento",
    description: "Cardio vertical com grande demanda de membros inferiores.",
    executionInstructions: "Suba degraus mantendo ritmo controlado e apoio estável dos pés.",
    breathingTips: "Respire em cadência constante, ajustando ao esforço.",
    postureTips: "Evite se apoiar excessivamente nos corrimãos.",
    contraindications: "Ajuste a intensidade em casos de dor anterior no joelho.",
    commonMistakes: "Curvar o tronco e descarregar o peso nos braços.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-038",
    name: "Polichinelo",
    category: "Cardio",
    muscleCategory: "Cardiorrespiratório",
    muscleGroupPrimary: "Cardiorrespiratório",
    muscleGroupsSecondary: ["Deltoide lateral", "Panturrilhas", "Quadríceps"],
    movementType: "Cardio",
    bodyRegion: "Corpo inteiro",
    equipment: "Peso corporal",
    difficultyLevel: "Iniciante",
    exerciseType: "Condicionamento",
    description: "Exercício cardiovascular simples para aquecimento ou blocos metabólicos.",
    executionInstructions: "Alterne abertura de pernas e braços acima da cabeça em ritmo contínuo.",
    breathingTips: "Estabeleça uma respiração ritmada conforme a cadência.",
    postureTips: "Mantenha aterrissagem suave e joelhos alinhados.",
    contraindications: "Ajuste o impacto para iniciantes e alunos com desconforto articular.",
    commonMistakes: "Aterrissar pesado e perder coordenação dos braços.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-039",
    name: "Mountain climber",
    category: "Cardio",
    muscleCategory: "Cardiorrespiratório",
    muscleGroupPrimary: "Cardiorrespiratório",
    muscleGroupsSecondary: ["Core", "Flexores do quadril", "Deltoide anterior"],
    movementType: "Cardio",
    bodyRegion: "Corpo inteiro",
    equipment: "Peso corporal",
    difficultyLevel: "Intermediário",
    exerciseType: "Condicionamento",
    description: "Cardio em apoio de braços com demanda de estabilidade do tronco.",
    executionInstructions: "Em prancha alta, alterne a aproximação dos joelhos ao peito em ritmo controlado.",
    breathingTips: "Respire de forma cadenciada sem prender o ar.",
    postureTips: "Mantenha ombros empilhados sobre as mãos e quadril estável.",
    contraindications: "Modere velocidade em sensibilidade de punhos ou ombros.",
    commonMistakes: "Subir demais o quadril e perder a linha corporal.",
    durationLimitSeconds: 6,
  },
  {
    id: "ex-lib-040",
    name: "Bike air",
    category: "Cardio",
    muscleCategory: "Cardiorrespiratório",
    muscleGroupPrimary: "Cardiorrespiratório",
    muscleGroupsSecondary: ["Quadríceps", "Glúteo máximo", "Membros superiores"],
    movementType: "Cardio",
    bodyRegion: "Corpo inteiro",
    equipment: "Bicicleta",
    difficultyLevel: "Avançado",
    exerciseType: "Condicionamento",
    description: "Cardio intervalado de alta intensidade em bicicleta com braços.",
    executionInstructions: "Empurre e puxe os manetes mantendo cadência forte durante o intervalo planejado.",
    breathingTips: "Use respiração rápida e ritmada para sustentar picos de intensidade.",
    postureTips: "Mantenha tronco firme e ajuste o assento antes de iniciar.",
    contraindications: "Exige progressão para iniciantes e controle em alunos descondicionados.",
    commonMistakes: "Começar rápido demais e perder consistência no intervalo.",
    durationLimitSeconds: 6,
  },
];

export const EXERCISE_LIBRARY_SEED: ExerciseLibraryItem[] = seedExercises.map((exercise) => ({
  ...exercise,
  slug: slugifyExerciseName(exercise.name),
  isActive: true,
  isGlobal: true,
  createdBy: null,
  createdAt,
  updatedAt: createdAt,
}));
