import type {
  ExerciseBodyRegion,
  ExerciseDifficultyLevel,
  ExerciseLaterality,
  ExerciseLibraryItem,
  ExerciseMechanicalType,
  ExerciseMovementCategory,
  ExerciseMovementPlane,
  ExerciseMovementType,
  ExerciseType,
} from "@/types";

export type ExerciseCatalogEntry = {
  name: string;
  aliases: string[];
  muscleCategory: string;
  muscleGroupPrimary: string;
  muscleGroupsSecondary: string[];
  movementType: ExerciseMovementType;
  movementCategory: ExerciseMovementCategory;
  bodyRegion: ExerciseBodyRegion;
  equipment: string;
  difficultyLevel: ExerciseDifficultyLevel;
  exerciseType: ExerciseType;
  mechanicalType: ExerciseMechanicalType;
  laterality: ExerciseLaterality;
  movementPlane?: ExerciseMovementPlane | null;
};

function entry(value: ExerciseCatalogEntry): ExerciseCatalogEntry {
  return value;
}

export const EXERCISE_LIBRARY_CATALOG: ExerciseCatalogEntry[] = [
  entry({ name: "Supino reto", aliases: ["Supino reto com barra"], muscleCategory: "Peito", muscleGroupPrimary: "Peitoral maior", muscleGroupsSecondary: ["Deltoide anterior", "Tríceps braquial"], movementType: "Empurrar", movementCategory: "Empurrar horizontal", bodyRegion: "Membros superiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Supino inclinado", aliases: ["Supino inclinado com halteres"], muscleCategory: "Peito", muscleGroupPrimary: "Peitoral maior", muscleGroupsSecondary: ["Deltoide anterior", "Tríceps braquial"], movementType: "Empurrar", movementCategory: "Empurrar horizontal", bodyRegion: "Membros superiores", equipment: "Banco inclinado", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Supino declinado", aliases: [], muscleCategory: "Peito", muscleGroupPrimary: "Peitoral maior", muscleGroupsSecondary: ["Deltoide anterior", "Tríceps braquial"], movementType: "Empurrar", movementCategory: "Empurrar horizontal", bodyRegion: "Membros superiores", equipment: "Banco declinado", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Crucifixo reto", aliases: [], muscleCategory: "Peito", muscleGroupPrimary: "Peitoral maior", muscleGroupsSecondary: ["Deltoide anterior"], movementType: "Empurrar", movementCategory: "Empurrar horizontal", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Crucifixo inclinado", aliases: [], muscleCategory: "Peito", muscleGroupPrimary: "Peitoral maior", muscleGroupsSecondary: ["Deltoide anterior"], movementType: "Empurrar", movementCategory: "Empurrar horizontal", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Crossover", aliases: ["Crossover na polia"], muscleCategory: "Peito", muscleGroupPrimary: "Peitoral maior", muscleGroupsSecondary: ["Deltoide anterior"], movementType: "Empurrar", movementCategory: "Empurrar horizontal", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Peck deck", aliases: ["Voador"], muscleCategory: "Peito", muscleGroupPrimary: "Peitoral maior", muscleGroupsSecondary: ["Deltoide anterior"], movementType: "Empurrar", movementCategory: "Empurrar horizontal", bodyRegion: "Membros superiores", equipment: "Máquina", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Pullover", aliases: [], muscleCategory: "Peito", muscleGroupPrimary: "Peitoral maior", muscleGroupsSecondary: ["Latíssimo do dorso", "Tríceps braquial"], movementType: "Empurrar", movementCategory: "Flexão de ombro", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),

  entry({ name: "Puxada frontal", aliases: ["Puxada frontal na polia"], muscleCategory: "Costas", muscleGroupPrimary: "Latíssimo do dorso", muscleGroupsSecondary: ["Bíceps braquial", "Romboides"], movementType: "Puxar", movementCategory: "Puxar vertical", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Frontal" }),
  entry({ name: "Puxada atrás", aliases: [], muscleCategory: "Costas", muscleGroupPrimary: "Latíssimo do dorso", muscleGroupsSecondary: ["Bíceps braquial", "Romboides"], movementType: "Puxar", movementCategory: "Puxar vertical", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Avançado", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Frontal" }),
  entry({ name: "Barra fixa", aliases: [], muscleCategory: "Costas", muscleGroupPrimary: "Latíssimo do dorso", muscleGroupsSecondary: ["Bíceps braquial", "Romboides"], movementType: "Puxar", movementCategory: "Puxar vertical", bodyRegion: "Membros superiores", equipment: "Barra fixa", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Frontal" }),
  entry({ name: "Remada curvada", aliases: ["Remada curvada com barra"], muscleCategory: "Costas", muscleGroupPrimary: "Latíssimo do dorso", muscleGroupsSecondary: ["Romboides", "Trapézio", "Bíceps braquial"], movementType: "Puxar", movementCategory: "Puxar horizontal", bodyRegion: "Membros superiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Remada unilateral", aliases: [], muscleCategory: "Costas", muscleGroupPrimary: "Latíssimo do dorso", muscleGroupsSecondary: ["Romboides", "Bíceps braquial"], movementType: "Puxar", movementCategory: "Puxar horizontal", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Unilateral", movementPlane: "Transversal" }),
  entry({ name: "Remada cavalinho", aliases: [], muscleCategory: "Costas", muscleGroupPrimary: "Latíssimo do dorso", muscleGroupsSecondary: ["Romboides", "Trapézio", "Bíceps braquial"], movementType: "Puxar", movementCategory: "Puxar horizontal", bodyRegion: "Membros superiores", equipment: "Barra T", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Remada baixa", aliases: [], muscleCategory: "Costas", muscleGroupPrimary: "Latíssimo do dorso", muscleGroupsSecondary: ["Romboides", "Bíceps braquial"], movementType: "Puxar", movementCategory: "Puxar horizontal", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Remada alta", aliases: [], muscleCategory: "Costas", muscleGroupPrimary: "Trapézio", muscleGroupsSecondary: ["Deltoide posterior", "Romboides"], movementType: "Puxar", movementCategory: "Puxar horizontal", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Pulldown", aliases: ["Pulldown na polia"], muscleCategory: "Costas", muscleGroupPrimary: "Latíssimo do dorso", muscleGroupsSecondary: ["Reto abdominal", "Tríceps braquial"], movementType: "Puxar", movementCategory: "Flexão de ombro", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Levantamento terra", aliases: [], muscleCategory: "Corpo inteiro", muscleGroupPrimary: "Posterior de coxa", muscleGroupsSecondary: ["Glúteo máximo", "Eretores da espinha", "Trapézio"], movementType: "Levantar", movementCategory: "Hinge", bodyRegion: "Corpo inteiro", equipment: "Barra", difficultyLevel: "Avançado", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),

  entry({ name: "Desenvolvimento militar", aliases: [], muscleCategory: "Ombros", muscleGroupPrimary: "Deltoide anterior", muscleGroupsSecondary: ["Deltoide lateral", "Tríceps braquial"], movementType: "Empurrar", movementCategory: "Empurrar vertical", bodyRegion: "Membros superiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Frontal" }),
  entry({ name: "Desenvolvimento com halteres", aliases: [], muscleCategory: "Ombros", muscleGroupPrimary: "Deltoide anterior", muscleGroupsSecondary: ["Deltoide lateral", "Tríceps braquial"], movementType: "Empurrar", movementCategory: "Empurrar vertical", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Frontal" }),
  entry({ name: "Elevação lateral", aliases: [], muscleCategory: "Ombros", muscleGroupPrimary: "Deltoide lateral", muscleGroupsSecondary: ["Trapézio"], movementType: "Empurrar", movementCategory: "Abdução de ombro", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Frontal" }),
  entry({ name: "Elevação frontal", aliases: [], muscleCategory: "Ombros", muscleGroupPrimary: "Deltoide anterior", muscleGroupsSecondary: ["Trapézio"], movementType: "Empurrar", movementCategory: "Flexão de ombro", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Crucifixo invertido", aliases: [], muscleCategory: "Ombros", muscleGroupPrimary: "Deltoide posterior", muscleGroupsSecondary: ["Romboides", "Trapézio"], movementType: "Puxar", movementCategory: "Puxar horizontal", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Face pull", aliases: [], muscleCategory: "Ombros", muscleGroupPrimary: "Deltoide posterior", muscleGroupsSecondary: ["Trapézio", "Romboides"], movementType: "Puxar", movementCategory: "Retração escapular", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Ativação", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Encolhimento", aliases: [], muscleCategory: "Ombros", muscleGroupPrimary: "Trapézio", muscleGroupsSecondary: [], movementType: "Puxar", movementCategory: "Retração escapular", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Frontal" }),
  entry({ name: "Arnold press", aliases: ["Desenvolvimento Arnold"], muscleCategory: "Ombros", muscleGroupPrimary: "Deltoide anterior", muscleGroupsSecondary: ["Deltoide lateral", "Tríceps braquial"], movementType: "Empurrar", movementCategory: "Empurrar vertical", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Multiplanar" }),

  entry({ name: "Rosca direta", aliases: ["Rosca direta com barra"], muscleCategory: "Bíceps", muscleGroupPrimary: "Bíceps braquial", muscleGroupsSecondary: ["Braquial", "Antebraços"], movementType: "Puxar", movementCategory: "Flexão de cotovelo", bodyRegion: "Membros superiores", equipment: "Barra", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Rosca alternada", aliases: [], muscleCategory: "Bíceps", muscleGroupPrimary: "Bíceps braquial", muscleGroupsSecondary: ["Braquial", "Antebraços"], movementType: "Puxar", movementCategory: "Flexão de cotovelo", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Unilateral", movementPlane: "Sagital" }),
  entry({ name: "Rosca martelo", aliases: [], muscleCategory: "Bíceps", muscleGroupPrimary: "Braquial", muscleGroupsSecondary: ["Bíceps braquial", "Antebraços"], movementType: "Puxar", movementCategory: "Flexão de cotovelo", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Unilateral", movementPlane: "Sagital" }),
  entry({ name: "Rosca concentrada", aliases: [], muscleCategory: "Bíceps", muscleGroupPrimary: "Bíceps braquial", muscleGroupsSecondary: ["Braquial"], movementType: "Puxar", movementCategory: "Flexão de cotovelo", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Unilateral", movementPlane: "Sagital" }),
  entry({ name: "Rosca Scott", aliases: [], muscleCategory: "Bíceps", muscleGroupPrimary: "Bíceps braquial", muscleGroupsSecondary: ["Braquial"], movementType: "Puxar", movementCategory: "Flexão de cotovelo", bodyRegion: "Membros superiores", equipment: "Banco Scott", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Rosca inclinada", aliases: [], muscleCategory: "Bíceps", muscleGroupPrimary: "Bíceps braquial", muscleGroupsSecondary: ["Braquial"], movementType: "Puxar", movementCategory: "Flexão de cotovelo", bodyRegion: "Membros superiores", equipment: "Banco inclinado", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Rosca inversa", aliases: [], muscleCategory: "Antebraço", muscleGroupPrimary: "Antebraços", muscleGroupsSecondary: ["Braquial", "Bíceps braquial"], movementType: "Puxar", movementCategory: "Flexão de cotovelo", bodyRegion: "Membros superiores", equipment: "Barra", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Rosca no cabo", aliases: [], muscleCategory: "Bíceps", muscleGroupPrimary: "Bíceps braquial", muscleGroupsSecondary: ["Braquial"], movementType: "Puxar", movementCategory: "Flexão de cotovelo", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),

  entry({ name: "Tríceps pulley", aliases: [], muscleCategory: "Tríceps", muscleGroupPrimary: "Tríceps braquial", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Extensão de cotovelo", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Tríceps corda", aliases: ["Tríceps na polia com corda"], muscleCategory: "Tríceps", muscleGroupPrimary: "Tríceps braquial", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Extensão de cotovelo", bodyRegion: "Membros superiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Tríceps francês", aliases: [], muscleCategory: "Tríceps", muscleGroupPrimary: "Tríceps braquial", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Extensão de cotovelo", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Unilateral", movementPlane: "Sagital" }),
  entry({ name: "Tríceps testa", aliases: [], muscleCategory: "Tríceps", muscleGroupPrimary: "Tríceps braquial", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Extensão de cotovelo", bodyRegion: "Membros superiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Tríceps banco", aliases: [], muscleCategory: "Tríceps", muscleGroupPrimary: "Tríceps braquial", muscleGroupsSecondary: ["Deltoide anterior", "Peitoral maior"], movementType: "Empurrar", movementCategory: "Extensão de cotovelo", bodyRegion: "Membros superiores", equipment: "Banco", difficultyLevel: "Intermediário", exerciseType: "Resistência", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Tríceps coice", aliases: [], muscleCategory: "Tríceps", muscleGroupPrimary: "Tríceps braquial", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Extensão de cotovelo", bodyRegion: "Membros superiores", equipment: "Halteres", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Unilateral", movementPlane: "Sagital" }),
  entry({ name: "Paralelas", aliases: [], muscleCategory: "Tríceps", muscleGroupPrimary: "Tríceps braquial", muscleGroupsSecondary: ["Peitoral maior", "Deltoide anterior"], movementType: "Empurrar", movementCategory: "Empurrar vertical", bodyRegion: "Membros superiores", equipment: "Paralelas", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Supino fechado", aliases: [], muscleCategory: "Tríceps", muscleGroupPrimary: "Tríceps braquial", muscleGroupsSecondary: ["Peitoral maior", "Deltoide anterior"], movementType: "Empurrar", movementCategory: "Empurrar horizontal", bodyRegion: "Membros superiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Transversal" }),

  entry({ name: "Agachamento livre", aliases: [], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: ["Glúteo máximo", "Core"], movementType: "Agachar", movementCategory: "Agachar", bodyRegion: "Membros inferiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Agachamento frontal", aliases: [], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: ["Glúteo máximo", "Core"], movementType: "Agachar", movementCategory: "Agachar", bodyRegion: "Membros inferiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Agachamento sumô", aliases: [], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Adutores", muscleGroupsSecondary: ["Glúteo máximo", "Quadríceps"], movementType: "Agachar", movementCategory: "Agachar", bodyRegion: "Membros inferiores", equipment: "Halteres", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Leg press", aliases: ["Leg press 45°"], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: ["Glúteo máximo", "Posterior de coxa"], movementType: "Empurrar", movementCategory: "Agachar", bodyRegion: "Membros inferiores", equipment: "Leg press", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Cadeira extensora", aliases: [], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Extensão de joelho", bodyRegion: "Membros inferiores", equipment: "Máquina", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Afundo", aliases: [], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: ["Glúteo máximo", "Posterior de coxa"], movementType: "Agachar", movementCategory: "Avanço", bodyRegion: "Membros inferiores", equipment: "Halteres", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Unilateral", movementPlane: "Sagital" }),
  entry({ name: "Passada", aliases: [], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: ["Glúteo máximo", "Posterior de coxa"], movementType: "Locomover", movementCategory: "Avanço", bodyRegion: "Membros inferiores", equipment: "Halteres", difficultyLevel: "Intermediário", exerciseType: "Condicionamento", mechanicalType: "Composto", laterality: "Unilateral", movementPlane: "Sagital" }),
  entry({ name: "Hack squat", aliases: ["Agachamento hack"], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: ["Glúteo máximo"], movementType: "Agachar", movementCategory: "Agachar", bodyRegion: "Membros inferiores", equipment: "Hack machine", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Agachamento búlgaro", aliases: [], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: ["Glúteo máximo", "Posterior de coxa"], movementType: "Agachar", movementCategory: "Avanço", bodyRegion: "Membros inferiores", equipment: "Banco", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Unilateral", movementPlane: "Sagital" }),
  entry({ name: "Smith squat", aliases: ["Agachamento no smith"], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: ["Glúteo máximo"], movementType: "Agachar", movementCategory: "Agachar", bodyRegion: "Membros inferiores", equipment: "Smith", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Stiff", aliases: [], muscleCategory: "Posterior de coxa", muscleGroupPrimary: "Posterior de coxa", muscleGroupsSecondary: ["Glúteo máximo", "Eretores da espinha"], movementType: "Levantar", movementCategory: "Hinge", bodyRegion: "Membros inferiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Levantamento terra romeno", aliases: ["Terra romeno"], muscleCategory: "Posterior de coxa", muscleGroupPrimary: "Posterior de coxa", muscleGroupsSecondary: ["Glúteo máximo", "Eretores da espinha"], movementType: "Levantar", movementCategory: "Hinge", bodyRegion: "Membros inferiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Elevação pélvica", aliases: ["Hip thrust com barra"], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Glúteo máximo", muscleGroupsSecondary: ["Posterior de coxa", "Core"], movementType: "Levantar", movementCategory: "Hinge", bodyRegion: "Membros inferiores", equipment: "Barra", difficultyLevel: "Intermediário", exerciseType: "Hipertrofia", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Glute bridge", aliases: ["Ponte de glúteos"], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Glúteo máximo", muscleGroupsSecondary: ["Posterior de coxa", "Core"], movementType: "Levantar", movementCategory: "Hinge", bodyRegion: "Membros inferiores", equipment: "Peso corporal", difficultyLevel: "Iniciante", exerciseType: "Ativação", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Coice no cabo", aliases: [], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Glúteo máximo", muscleGroupsSecondary: ["Posterior de coxa"], movementType: "Empurrar", movementCategory: "Extensão de quadril", bodyRegion: "Membros inferiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Unilateral", movementPlane: "Sagital" }),
  entry({ name: "Abdução de quadril", aliases: [], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Glúteo médio", muscleGroupsSecondary: ["Glúteo máximo"], movementType: "Empurrar", movementCategory: "Abdução de quadril", bodyRegion: "Membros inferiores", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Ativação", mechanicalType: "Isolado", laterality: "Unilateral", movementPlane: "Frontal" }),
  entry({ name: "Adutora", aliases: ["Cadeira adutora"], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Adutores", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Adução de quadril", bodyRegion: "Membros inferiores", equipment: "Máquina", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Frontal" }),
  entry({ name: "Abdutora", aliases: ["Cadeira abdutora"], muscleCategory: "Quadríceps e glúteos", muscleGroupPrimary: "Glúteo médio", muscleGroupsSecondary: ["Glúteo máximo"], movementType: "Empurrar", movementCategory: "Abdução de quadril", bodyRegion: "Membros inferiores", equipment: "Máquina", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Frontal" }),

  entry({ name: "Mesa flexora", aliases: [], muscleCategory: "Posterior de coxa", muscleGroupPrimary: "Posterior de coxa", muscleGroupsSecondary: ["Panturrilhas"], movementType: "Puxar", movementCategory: "Flexão de joelho", bodyRegion: "Membros inferiores", equipment: "Máquina", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Cadeira flexora", aliases: [], muscleCategory: "Posterior de coxa", muscleGroupPrimary: "Posterior de coxa", muscleGroupsSecondary: ["Panturrilhas"], movementType: "Puxar", movementCategory: "Flexão de joelho", bodyRegion: "Membros inferiores", equipment: "Máquina", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Good morning", aliases: [], muscleCategory: "Posterior de coxa", muscleGroupPrimary: "Posterior de coxa", muscleGroupsSecondary: ["Glúteo máximo", "Eretores da espinha"], movementType: "Levantar", movementCategory: "Hinge", bodyRegion: "Membros inferiores", equipment: "Barra", difficultyLevel: "Avançado", exerciseType: "Técnica", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),

  entry({ name: "Panturrilha em pé", aliases: ["Panturrilha em pé na máquina"], muscleCategory: "Panturrilhas", muscleGroupPrimary: "Panturrilhas", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Flexão plantar", bodyRegion: "Membros inferiores", equipment: "Máquina", difficultyLevel: "Iniciante", exerciseType: "Resistência", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Panturrilha sentada", aliases: [], muscleCategory: "Panturrilhas", muscleGroupPrimary: "Panturrilhas", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Flexão plantar", bodyRegion: "Membros inferiores", equipment: "Máquina", difficultyLevel: "Iniciante", exerciseType: "Resistência", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Panturrilha no leg press", aliases: [], muscleCategory: "Panturrilhas", muscleGroupPrimary: "Panturrilhas", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Flexão plantar", bodyRegion: "Membros inferiores", equipment: "Leg press", difficultyLevel: "Iniciante", exerciseType: "Resistência", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Panturrilha no smith", aliases: [], muscleCategory: "Panturrilhas", muscleGroupPrimary: "Panturrilhas", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Flexão plantar", bodyRegion: "Membros inferiores", equipment: "Smith", difficultyLevel: "Iniciante", exerciseType: "Resistência", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),

  entry({ name: "Abdominal reto", aliases: ["Crunch"], muscleCategory: "Abdômen", muscleGroupPrimary: "Reto abdominal", muscleGroupsSecondary: ["Core"], movementType: "Estabilizar", movementCategory: "Flexão de tronco", bodyRegion: "Tronco", equipment: "Peso corporal", difficultyLevel: "Iniciante", exerciseType: "Ativação", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Abdominal infra", aliases: [], muscleCategory: "Abdômen", muscleGroupPrimary: "Reto abdominal", muscleGroupsSecondary: ["Flexores do quadril"], movementType: "Estabilizar", movementCategory: "Flexão de tronco", bodyRegion: "Tronco", equipment: "Peso corporal", difficultyLevel: "Iniciante", exerciseType: "Ativação", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Abdominal oblíquo", aliases: [], muscleCategory: "Abdômen", muscleGroupPrimary: "Oblíquos", muscleGroupsSecondary: ["Reto abdominal"], movementType: "Rotacionar", movementCategory: "Rotação de tronco", bodyRegion: "Tronco", equipment: "Peso corporal", difficultyLevel: "Iniciante", exerciseType: "Ativação", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Transversal" }),
  entry({ name: "Abdominal na polia", aliases: [], muscleCategory: "Abdômen", muscleGroupPrimary: "Reto abdominal", muscleGroupsSecondary: ["Oblíquos"], movementType: "Estabilizar", movementCategory: "Flexão de tronco", bodyRegion: "Tronco", equipment: "Cabo", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Prancha", aliases: ["Prancha frontal"], muscleCategory: "Abdômen", muscleGroupPrimary: "Core", muscleGroupsSecondary: ["Reto abdominal", "Oblíquos"], movementType: "Isométrico", movementCategory: "Anti-extensão", bodyRegion: "Tronco", equipment: "Peso corporal", difficultyLevel: "Iniciante", exerciseType: "Ativação", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Elevação de pernas", aliases: [], muscleCategory: "Abdômen", muscleGroupPrimary: "Reto abdominal", muscleGroupsSecondary: ["Flexores do quadril"], movementType: "Estabilizar", movementCategory: "Flexão de tronco", bodyRegion: "Tronco", equipment: "Barra fixa", difficultyLevel: "Intermediário", exerciseType: "Ativação", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Ab wheel", aliases: ["Roda abdominal"], muscleCategory: "Abdômen", muscleGroupPrimary: "Core", muscleGroupsSecondary: ["Reto abdominal", "Deltoide anterior"], movementType: "Estabilizar", movementCategory: "Anti-extensão", bodyRegion: "Tronco", equipment: "Roda abdominal", difficultyLevel: "Intermediário", exerciseType: "Força", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Russian twist", aliases: [], muscleCategory: "Abdômen", muscleGroupPrimary: "Oblíquos", muscleGroupsSecondary: ["Reto abdominal", "Flexores do quadril"], movementType: "Rotacionar", movementCategory: "Rotação de tronco", bodyRegion: "Tronco", equipment: "Peso corporal", difficultyLevel: "Intermediário", exerciseType: "Ativação", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Transversal" }),

  entry({ name: "Flexão de punho", aliases: [], muscleCategory: "Antebraço", muscleGroupPrimary: "Antebraços", muscleGroupsSecondary: [], movementType: "Puxar", movementCategory: "Flexão de cotovelo", bodyRegion: "Membros superiores", equipment: "Barra", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Extensão de punho", aliases: [], muscleCategory: "Antebraço", muscleGroupPrimary: "Antebraços", muscleGroupsSecondary: [], movementType: "Empurrar", movementCategory: "Extensão de cotovelo", bodyRegion: "Membros superiores", equipment: "Barra", difficultyLevel: "Iniciante", exerciseType: "Hipertrofia", mechanicalType: "Isolado", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Caminhada do fazendeiro", aliases: ["Farmer's walk", "Farmer walk com halteres"], muscleCategory: "Antebraço", muscleGroupPrimary: "Antebraços", muscleGroupsSecondary: ["Trapézio", "Core"], movementType: "Locomover", movementCategory: "Carregada", bodyRegion: "Corpo inteiro", equipment: "Halteres", difficultyLevel: "Intermediário", exerciseType: "Condicionamento", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Multiplanar" }),

  entry({ name: "Power clean", aliases: [], muscleCategory: "Corpo inteiro", muscleGroupPrimary: "Corpo inteiro", muscleGroupsSecondary: ["Posterior de coxa", "Quadríceps", "Trapézio"], movementType: "Levantar", movementCategory: "Potência", bodyRegion: "Corpo inteiro", equipment: "Barra", difficultyLevel: "Avançado", exerciseType: "Técnica", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Swing com kettlebell", aliases: ["Kettlebell swing"], muscleCategory: "Corpo inteiro", muscleGroupPrimary: "Posterior de coxa", muscleGroupsSecondary: ["Glúteo máximo", "Core"], movementType: "Levantar", movementCategory: "Hinge", bodyRegion: "Corpo inteiro", equipment: "Kettlebell", difficultyLevel: "Intermediário", exerciseType: "Condicionamento", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
  entry({ name: "Burpee", aliases: [], muscleCategory: "Corpo inteiro", muscleGroupPrimary: "Corpo inteiro", muscleGroupsSecondary: ["Peitoral maior", "Quadríceps", "Core"], movementType: "Locomover", movementCategory: "Locomoção", bodyRegion: "Corpo inteiro", equipment: "Peso corporal", difficultyLevel: "Intermediário", exerciseType: "Condicionamento", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Multiplanar" }),
  entry({ name: "Thruster", aliases: [], muscleCategory: "Corpo inteiro", muscleGroupPrimary: "Quadríceps", muscleGroupsSecondary: ["Deltoide anterior", "Glúteo máximo", "Tríceps braquial"], movementType: "Empurrar", movementCategory: "Empurrar vertical", bodyRegion: "Corpo inteiro", equipment: "Barra", difficultyLevel: "Avançado", exerciseType: "Condicionamento", mechanicalType: "Composto", laterality: "Bilateral", movementPlane: "Sagital" }),
];

export function createExerciseSeedFromCatalog(
  entryItem: ExerciseCatalogEntry,
  base: Pick<ExerciseLibraryItem, "id" | "slug" | "createdAt" | "updatedAt" | "isActive" | "isGlobal" | "createdBy">,
): ExerciseLibraryItem {
  return {
    ...base,
    name: entryItem.name,
    category: "Musculação",
    muscleCategory: entryItem.muscleCategory,
    muscleGroupPrimary: entryItem.muscleGroupPrimary,
    muscleGroupsSecondary: entryItem.muscleGroupsSecondary,
    movementType: entryItem.movementType,
    movementCategory: entryItem.movementCategory,
    bodyRegion: entryItem.bodyRegion,
    equipment: entryItem.equipment,
    difficultyLevel: entryItem.difficultyLevel,
    exerciseType: entryItem.exerciseType,
    mechanicalType: entryItem.mechanicalType,
    laterality: entryItem.laterality,
    movementPlane: entryItem.movementPlane ?? null,
    aliases: entryItem.aliases,
    description: "",
    executionInstructions: "",
    breathingTips: "",
    postureTips: "",
    contraindications: "",
    commonMistakes: "",
    videoUrl: null,
    videoStoragePath: null,
    thumbnailUrl: null,
    thumbnailStoragePath: null,
    durationLimitSeconds: 6,
  };
}
