export const MUSCLE_CATEGORIES = [
  "Peito",
  "Costas",
  "Ombros",
  "Bíceps",
  "Tríceps",
  "Antebraço",
  "Abdômen",
  "Glúteos",
  "Quadríceps",
  "Posterior de coxa",
  "Panturrilhas",
  "Lombar",
  "Corpo inteiro",
  "Mobilidade / alongamento",
  "Cardiorrespiratório",
] as const;

export const MUSCLE_GROUP_OPTIONS = [
  "Peitoral maior",
  "Peitoral menor",
  "Latíssimo do dorso",
  "Trapézio",
  "Romboides",
  "Deltoide anterior",
  "Deltoide lateral",
  "Deltoide posterior",
  "Bíceps braquial",
  "Braquial",
  "Tríceps braquial",
  "Antebraços",
  "Reto abdominal",
  "Oblíquos",
  "Eretores da espinha",
  "Glúteo máximo",
  "Glúteo médio",
  "Quadríceps",
  "Posterior de coxa",
  "Adutores",
  "Panturrilhas",
  "Tibial anterior",
  "Core",
  "Corpo inteiro",
  "Mobilidade",
  "Cardiorrespiratório",
] as const;

export const EXERCISE_EQUIPMENT_SUGGESTIONS = [
  "Peso corporal",
  "Halteres",
  "Barra",
  "Cabo",
  "Máquina",
  "Kettlebell",
  "Faixa elástica",
  "Banco",
  "Bola suíça",
  "TRX",
] as const;
