insert into public.exercises (
  name,
  slug,
  category,
  muscle_category,
  muscle_group_primary,
  muscle_groups_secondary,
  movement_type,
  body_region,
  equipment,
  difficulty_level,
  exercise_type,
  duration_limit_seconds,
  is_active,
  is_global
)
values
  ('Supino reto', 'supino-reto', 'Musculação', 'Peito', 'Peitoral maior', array['Deltoide anterior','Tríceps braquial'], 'Empurrar', 'Membros superiores', 'Barra', 'Intermediário', 'Força', 6, true, true),
  ('Supino inclinado', 'supino-inclinado', 'Musculação', 'Peito', 'Peitoral maior', array['Deltoide anterior','Tríceps braquial'], 'Empurrar', 'Membros superiores', 'Banco inclinado', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Supino declinado', 'supino-declinado', 'Musculação', 'Peito', 'Peitoral maior', array['Deltoide anterior','Tríceps braquial'], 'Empurrar', 'Membros superiores', 'Banco declinado', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Crucifixo reto', 'crucifixo-reto', 'Musculação', 'Peito', 'Peitoral maior', array['Deltoide anterior'], 'Empurrar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Crucifixo inclinado', 'crucifixo-inclinado', 'Musculação', 'Peito', 'Peitoral maior', array['Deltoide anterior'], 'Empurrar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Crossover', 'crossover', 'Musculação', 'Peito', 'Peitoral maior', array['Deltoide anterior'], 'Empurrar', 'Membros superiores', 'Cabo', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Peck deck', 'peck-deck', 'Musculação', 'Peito', 'Peitoral maior', array['Deltoide anterior'], 'Empurrar', 'Membros superiores', 'Máquina', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Pullover', 'pullover', 'Musculação', 'Peito', 'Peitoral maior', array['Latíssimo do dorso','Tríceps braquial'], 'Empurrar', 'Membros superiores', 'Halteres', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Puxada frontal', 'puxada-frontal', 'Musculação', 'Costas', 'Latíssimo do dorso', array['Bíceps braquial','Romboides'], 'Puxar', 'Membros superiores', 'Cabo', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Puxada atrás', 'puxada-atras', 'Musculação', 'Costas', 'Latíssimo do dorso', array['Bíceps braquial','Romboides'], 'Puxar', 'Membros superiores', 'Cabo', 'Avançado', 'Hipertrofia', 6, true, true),
  ('Barra fixa', 'barra-fixa', 'Musculação', 'Costas', 'Latíssimo do dorso', array['Bíceps braquial','Romboides'], 'Puxar', 'Membros superiores', 'Barra fixa', 'Intermediário', 'Força', 6, true, true),
  ('Remada curvada', 'remada-curvada', 'Musculação', 'Costas', 'Latíssimo do dorso', array['Romboides','Trapézio','Bíceps braquial'], 'Puxar', 'Membros superiores', 'Barra', 'Intermediário', 'Força', 6, true, true),
  ('Remada unilateral', 'remada-unilateral', 'Musculação', 'Costas', 'Latíssimo do dorso', array['Romboides','Bíceps braquial'], 'Puxar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Remada cavalinho', 'remada-cavalinho', 'Musculação', 'Costas', 'Latíssimo do dorso', array['Romboides','Trapézio','Bíceps braquial'], 'Puxar', 'Membros superiores', 'Barra T', 'Intermediário', 'Força', 6, true, true),
  ('Remada baixa', 'remada-baixa', 'Musculação', 'Costas', 'Latíssimo do dorso', array['Romboides','Bíceps braquial'], 'Puxar', 'Membros superiores', 'Cabo', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Remada alta', 'remada-alta', 'Musculação', 'Costas', 'Trapézio', array['Deltoide posterior','Romboides'], 'Puxar', 'Membros superiores', 'Cabo', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Pulldown', 'pulldown', 'Musculação', 'Costas', 'Latíssimo do dorso', array['Reto abdominal','Tríceps braquial'], 'Puxar', 'Membros superiores', 'Cabo', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Levantamento terra', 'levantamento-terra', 'Musculação', 'Corpo inteiro', 'Posterior de coxa', array['Glúteo máximo','Eretores da espinha','Trapézio'], 'Levantar', 'Corpo inteiro', 'Barra', 'Avançado', 'Força', 6, true, true),
  ('Desenvolvimento militar', 'desenvolvimento-militar', 'Musculação', 'Ombros', 'Deltoide anterior', array['Deltoide lateral','Tríceps braquial'], 'Empurrar', 'Membros superiores', 'Barra', 'Intermediário', 'Força', 6, true, true),
  ('Elevação frontal', 'elevacao-frontal', 'Musculação', 'Ombros', 'Deltoide anterior', array['Trapézio'], 'Empurrar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Crucifixo invertido', 'crucifixo-invertido', 'Musculação', 'Ombros', 'Deltoide posterior', array['Romboides','Trapézio'], 'Puxar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Face pull', 'face-pull', 'Musculação', 'Ombros', 'Deltoide posterior', array['Trapézio','Romboides'], 'Puxar', 'Membros superiores', 'Cabo', 'Iniciante', 'Ativação', 6, true, true),
  ('Encolhimento', 'encolhimento', 'Musculação', 'Ombros', 'Trapézio', array[]::text[], 'Puxar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Arnold press', 'arnold-press', 'Musculação', 'Ombros', 'Deltoide anterior', array['Deltoide lateral','Tríceps braquial'], 'Empurrar', 'Membros superiores', 'Halteres', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Rosca direta', 'rosca-direta', 'Musculação', 'Bíceps', 'Bíceps braquial', array['Braquial','Antebraços'], 'Puxar', 'Membros superiores', 'Barra', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Rosca alternada', 'rosca-alternada', 'Musculação', 'Bíceps', 'Bíceps braquial', array['Braquial','Antebraços'], 'Puxar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Rosca martelo', 'rosca-martelo', 'Musculação', 'Bíceps', 'Braquial', array['Bíceps braquial','Antebraços'], 'Puxar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Rosca concentrada', 'rosca-concentrada', 'Musculação', 'Bíceps', 'Bíceps braquial', array['Braquial'], 'Puxar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Rosca Scott', 'rosca-scott', 'Musculação', 'Bíceps', 'Bíceps braquial', array['Braquial'], 'Puxar', 'Membros superiores', 'Banco Scott', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Rosca inclinada', 'rosca-inclinada', 'Musculação', 'Bíceps', 'Bíceps braquial', array['Braquial'], 'Puxar', 'Membros superiores', 'Banco inclinado', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Rosca inversa', 'rosca-inversa', 'Musculação', 'Antebraço', 'Antebraços', array['Braquial','Bíceps braquial'], 'Puxar', 'Membros superiores', 'Barra', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Rosca no cabo', 'rosca-no-cabo', 'Musculação', 'Bíceps', 'Bíceps braquial', array['Braquial'], 'Puxar', 'Membros superiores', 'Cabo', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Tríceps pulley', 'triceps-pulley', 'Musculação', 'Tríceps', 'Tríceps braquial', array[]::text[], 'Empurrar', 'Membros superiores', 'Cabo', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Tríceps corda', 'triceps-corda', 'Musculação', 'Tríceps', 'Tríceps braquial', array[]::text[], 'Empurrar', 'Membros superiores', 'Cabo', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Tríceps francês', 'triceps-frances', 'Musculação', 'Tríceps', 'Tríceps braquial', array[]::text[], 'Empurrar', 'Membros superiores', 'Halteres', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Tríceps testa', 'triceps-testa', 'Musculação', 'Tríceps', 'Tríceps braquial', array[]::text[], 'Empurrar', 'Membros superiores', 'Barra', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Tríceps banco', 'triceps-banco', 'Musculação', 'Tríceps', 'Tríceps braquial', array['Deltoide anterior','Peitoral maior'], 'Empurrar', 'Membros superiores', 'Banco', 'Intermediário', 'Resistência', 6, true, true),
  ('Tríceps coice', 'triceps-coice', 'Musculação', 'Tríceps', 'Tríceps braquial', array[]::text[], 'Empurrar', 'Membros superiores', 'Halteres', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Paralelas', 'paralelas', 'Musculação', 'Tríceps', 'Tríceps braquial', array['Peitoral maior','Deltoide anterior'], 'Empurrar', 'Membros superiores', 'Paralelas', 'Intermediário', 'Força', 6, true, true),
  ('Supino fechado', 'supino-fechado', 'Musculação', 'Tríceps', 'Tríceps braquial', array['Peitoral maior','Deltoide anterior'], 'Empurrar', 'Membros superiores', 'Barra', 'Intermediário', 'Força', 6, true, true),
  ('Agachamento frontal', 'agachamento-frontal', 'Musculação', 'Quadríceps e glúteos', 'Quadríceps', array['Glúteo máximo','Core'], 'Agachar', 'Membros inferiores', 'Barra', 'Intermediário', 'Força', 6, true, true),
  ('Agachamento sumô', 'agachamento-sumo', 'Musculação', 'Quadríceps e glúteos', 'Adutores', array['Glúteo máximo','Quadríceps'], 'Agachar', 'Membros inferiores', 'Halteres', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Leg press', 'leg-press', 'Musculação', 'Quadríceps e glúteos', 'Quadríceps', array['Glúteo máximo','Posterior de coxa'], 'Empurrar', 'Membros inferiores', 'Leg press', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Cadeira extensora', 'cadeira-extensora', 'Musculação', 'Quadríceps e glúteos', 'Quadríceps', array[]::text[], 'Empurrar', 'Membros inferiores', 'Máquina', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Afundo', 'afundo', 'Musculação', 'Quadríceps e glúteos', 'Quadríceps', array['Glúteo máximo','Posterior de coxa'], 'Agachar', 'Membros inferiores', 'Halteres', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Passada', 'passada', 'Musculação', 'Quadríceps e glúteos', 'Quadríceps', array['Glúteo máximo','Posterior de coxa'], 'Locomover', 'Membros inferiores', 'Halteres', 'Intermediário', 'Condicionamento', 6, true, true),
  ('Hack squat', 'hack-squat', 'Musculação', 'Quadríceps e glúteos', 'Quadríceps', array['Glúteo máximo'], 'Agachar', 'Membros inferiores', 'Hack machine', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Agachamento búlgaro', 'agachamento-bulgaro', 'Musculação', 'Quadríceps e glúteos', 'Quadríceps', array['Glúteo máximo','Posterior de coxa'], 'Agachar', 'Membros inferiores', 'Banco', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Smith squat', 'smith-squat', 'Musculação', 'Quadríceps e glúteos', 'Quadríceps', array['Glúteo máximo'], 'Agachar', 'Membros inferiores', 'Smith', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Stiff', 'stiff', 'Musculação', 'Posterior de coxa', 'Posterior de coxa', array['Glúteo máximo','Eretores da espinha'], 'Levantar', 'Membros inferiores', 'Barra', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Terra romeno', 'terra-romeno', 'Musculação', 'Posterior de coxa', 'Posterior de coxa', array['Glúteo máximo','Eretores da espinha'], 'Levantar', 'Membros inferiores', 'Barra', 'Intermediário', 'Força', 6, true, true),
  ('Elevação pélvica', 'elevacao-pelvica', 'Musculação', 'Quadríceps e glúteos', 'Glúteo máximo', array['Posterior de coxa','Core'], 'Levantar', 'Membros inferiores', 'Barra', 'Intermediário', 'Hipertrofia', 6, true, true),
  ('Glute bridge', 'glute-bridge', 'Musculação', 'Quadríceps e glúteos', 'Glúteo máximo', array['Posterior de coxa','Core'], 'Levantar', 'Membros inferiores', 'Peso corporal', 'Iniciante', 'Ativação', 6, true, true),
  ('Coice no cabo', 'coice-no-cabo', 'Musculação', 'Quadríceps e glúteos', 'Glúteo máximo', array['Posterior de coxa'], 'Empurrar', 'Membros inferiores', 'Cabo', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Abdução de quadril', 'abducao-de-quadril', 'Musculação', 'Quadríceps e glúteos', 'Glúteo médio', array['Glúteo máximo'], 'Empurrar', 'Membros inferiores', 'Cabo', 'Iniciante', 'Ativação', 6, true, true),
  ('Adutora', 'adutora', 'Musculação', 'Quadríceps e glúteos', 'Adutores', array[]::text[], 'Empurrar', 'Membros inferiores', 'Máquina', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Abdutora', 'abdutora', 'Musculação', 'Quadríceps e glúteos', 'Glúteo médio', array['Glúteo máximo'], 'Empurrar', 'Membros inferiores', 'Máquina', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Mesa flexora', 'mesa-flexora', 'Musculação', 'Posterior de coxa', 'Posterior de coxa', array['Panturrilhas'], 'Puxar', 'Membros inferiores', 'Máquina', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Cadeira flexora', 'cadeira-flexora', 'Musculação', 'Posterior de coxa', 'Posterior de coxa', array['Panturrilhas'], 'Puxar', 'Membros inferiores', 'Máquina', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Good morning', 'good-morning', 'Musculação', 'Posterior de coxa', 'Posterior de coxa', array['Glúteo máximo','Eretores da espinha'], 'Levantar', 'Membros inferiores', 'Barra', 'Avançado', 'Técnica', 6, true, true),
  ('Panturrilha em pé', 'panturrilha-em-pe', 'Musculação', 'Panturrilhas', 'Panturrilhas', array[]::text[], 'Empurrar', 'Membros inferiores', 'Máquina', 'Iniciante', 'Resistência', 6, true, true),
  ('Panturrilha sentada', 'panturrilha-sentada', 'Musculação', 'Panturrilhas', 'Panturrilhas', array[]::text[], 'Empurrar', 'Membros inferiores', 'Máquina', 'Iniciante', 'Resistência', 6, true, true),
  ('Panturrilha no leg press', 'panturrilha-no-leg-press', 'Musculação', 'Panturrilhas', 'Panturrilhas', array[]::text[], 'Empurrar', 'Membros inferiores', 'Leg press', 'Iniciante', 'Resistência', 6, true, true),
  ('Panturrilha no smith', 'panturrilha-no-smith', 'Musculação', 'Panturrilhas', 'Panturrilhas', array[]::text[], 'Empurrar', 'Membros inferiores', 'Smith', 'Iniciante', 'Resistência', 6, true, true),
  ('Abdominal reto', 'abdominal-reto', 'Musculação', 'Abdômen', 'Reto abdominal', array['Core'], 'Estabilizar', 'Tronco', 'Peso corporal', 'Iniciante', 'Ativação', 6, true, true),
  ('Abdominal infra', 'abdominal-infra', 'Musculação', 'Abdômen', 'Reto abdominal', array['Flexores do quadril'], 'Estabilizar', 'Tronco', 'Peso corporal', 'Iniciante', 'Ativação', 6, true, true),
  ('Abdominal oblíquo', 'abdominal-obliquo', 'Musculação', 'Abdômen', 'Oblíquos', array['Reto abdominal'], 'Rotacionar', 'Tronco', 'Peso corporal', 'Iniciante', 'Ativação', 6, true, true),
  ('Abdominal na polia', 'abdominal-na-polia', 'Musculação', 'Abdômen', 'Reto abdominal', array['Oblíquos'], 'Estabilizar', 'Tronco', 'Cabo', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Crunch', 'crunch', 'Musculação', 'Abdômen', 'Reto abdominal', array['Core'], 'Estabilizar', 'Tronco', 'Peso corporal', 'Iniciante', 'Ativação', 6, true, true),
  ('Prancha', 'prancha', 'Musculação', 'Abdômen', 'Core', array['Reto abdominal','Oblíquos'], 'Isométrico', 'Tronco', 'Peso corporal', 'Iniciante', 'Ativação', 6, true, true),
  ('Elevação de pernas', 'elevacao-de-pernas', 'Musculação', 'Abdômen', 'Reto abdominal', array['Flexores do quadril'], 'Estabilizar', 'Tronco', 'Barra fixa', 'Intermediário', 'Ativação', 6, true, true),
  ('Ab wheel', 'ab-wheel', 'Musculação', 'Abdômen', 'Core', array['Reto abdominal','Deltoide anterior'], 'Estabilizar', 'Tronco', 'Roda abdominal', 'Intermediário', 'Força', 6, true, true),
  ('Russian twist', 'russian-twist', 'Musculação', 'Abdômen', 'Oblíquos', array['Reto abdominal','Flexores do quadril'], 'Rotacionar', 'Tronco', 'Peso corporal', 'Intermediário', 'Ativação', 6, true, true),
  ('Flexão de punho', 'flexao-de-punho', 'Musculação', 'Antebraço', 'Antebraços', array[]::text[], 'Puxar', 'Membros superiores', 'Barra', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Extensão de punho', 'extensao-de-punho', 'Musculação', 'Antebraço', 'Antebraços', array[]::text[], 'Empurrar', 'Membros superiores', 'Barra', 'Iniciante', 'Hipertrofia', 6, true, true),
  ('Farmer''s walk', 'farmers-walk', 'Musculação', 'Antebraço', 'Antebraços', array['Trapézio','Core'], 'Locomover', 'Corpo inteiro', 'Halteres', 'Intermediário', 'Condicionamento', 6, true, true),
  ('Power clean', 'power-clean', 'Musculação', 'Corpo inteiro', 'Corpo inteiro', array['Posterior de coxa','Quadríceps','Trapézio'], 'Levantar', 'Corpo inteiro', 'Barra', 'Avançado', 'Técnica', 6, true, true),
  ('Kettlebell swing', 'kettlebell-swing', 'Musculação', 'Corpo inteiro', 'Posterior de coxa', array['Glúteo máximo','Core'], 'Levantar', 'Corpo inteiro', 'Kettlebell', 'Intermediário', 'Condicionamento', 6, true, true),
  ('Burpee', 'burpee', 'Musculação', 'Corpo inteiro', 'Corpo inteiro', array['Peitoral maior','Quadríceps','Core'], 'Locomover', 'Corpo inteiro', 'Peso corporal', 'Intermediário', 'Condicionamento', 6, true, true),
  ('Thruster', 'thruster', 'Musculação', 'Corpo inteiro', 'Quadríceps', array['Deltoide anterior','Glúteo máximo','Tríceps braquial'], 'Empurrar', 'Corpo inteiro', 'Barra', 'Avançado', 'Condicionamento', 6, true, true)
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  muscle_category = excluded.muscle_category,
  muscle_group_primary = excluded.muscle_group_primary,
  muscle_groups_secondary = excluded.muscle_groups_secondary,
  movement_type = excluded.movement_type,
  body_region = excluded.body_region,
  equipment = excluded.equipment,
  difficulty_level = excluded.difficulty_level,
  exercise_type = excluded.exercise_type,
  duration_limit_seconds = excluded.duration_limit_seconds,
  is_active = excluded.is_active,
  is_global = excluded.is_global;
