insert into public.exercises (
  name,
  slug,
  category,
  muscle_category,
  muscle_group_primary,
  muscle_groups_secondary,
  movement_type,
  body_region,
  equipment,
  difficulty_level,
  exercise_type,
  duration_limit_seconds,
  is_active,
  is_global
)
values
  ('Flexão cervical', 'flexao-cervical', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Trapézio'], 'Mobilidade', 'Tronco', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Extensão cervical', 'extensao-cervical', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Trapézio'], 'Mobilidade', 'Tronco', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Rotação cervical', 'rotacao-cervical', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Trapézio'], 'Mobilidade', 'Tronco', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Inclinação lateral cervical', 'inclinacao-lateral-cervical', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Trapézio'], 'Mobilidade', 'Tronco', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Circundução de ombros', 'circunducao-de-ombros', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Deltoide anterior','Deltoide posterior'], 'Mobilidade', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Rotação de ombros', 'rotacao-de-ombros', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Manguito rotador','Deltoide posterior'], 'Mobilidade', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Elevação de ombros', 'elevacao-de-ombros', 'Mobilidade', 'Mobilidade', 'Trapézio', array['Deltoide lateral'], 'Mobilidade', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Shoulder pass through', 'shoulder-pass-through', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Deltoide anterior','Peitoral maior'], 'Mobilidade', 'Membros superiores', 'Bastão', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Wall slides', 'wall-slides', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Deltoide anterior','Trapézio'], 'Mobilidade', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Dislocamento com bastão', 'dislocamento-com-bastao', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Deltoide anterior','Peitoral maior'], 'Mobilidade', 'Membros superiores', 'Bastão', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Rotação torácica', 'rotacao-toracica', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Romboides','Eretores da espinha'], 'Mobilidade', 'Tronco', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Extensão torácica', 'extensao-toracica', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Eretores da espinha','Trapézio'], 'Mobilidade', 'Tronco', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Cat-cow', 'cat-cow', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Eretores da espinha','Core'], 'Mobilidade', 'Tronco', 'Peso corporal', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Open book', 'open-book', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Romboides','Oblíquos'], 'Mobilidade', 'Tronco', 'Peso corporal', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Thread the needle', 'thread-the-needle', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Romboides','Deltoide posterior'], 'Mobilidade', 'Tronco', 'Peso corporal', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Círculos de quadril', 'circulos-de-quadril', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Glúteo médio','Flexores do quadril'], 'Mobilidade', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Hip opener', 'hip-opener', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Glúteo médio','Adutores'], 'Mobilidade', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('90/90', '90-90', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Glúteo médio','Adutores'], 'Mobilidade', 'Membros inferiores', 'Peso corporal', 'Intermediário', 'Mobilidade', 6, true, true),
  ('Alongamento do flexor do quadril', 'alongamento-do-flexor-do-quadril', 'Alongamento', 'Alongamento', 'Flexores do quadril', array['Quadríceps'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento do piriforme', 'alongamento-do-piriforme', 'Alongamento', 'Alongamento', 'Glúteo máximo', array['Glúteo médio'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Frog stretch', 'frog-stretch', 'Alongamento', 'Alongamento', 'Adutores', array['Glúteo médio'], 'Alongamento', 'Membros inferiores', 'Peso corporal', 'Intermediário', 'Alongamento', 6, true, true),
  ('Cossack squat', 'cossack-squat', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Adutores','Glúteo máximo'], 'Mobilidade', 'Membros inferiores', 'Peso corporal', 'Intermediário', 'Mobilidade', 6, true, true),
  ('Pigeon pose', 'pigeon-pose', 'Alongamento', 'Alongamento', 'Glúteo máximo', array['Glúteo médio','Posterior de coxa'], 'Alongamento', 'Membros inferiores', 'Peso corporal', 'Intermediário', 'Alongamento', 6, true, true),
  ('Mobilidade de tornozelo na parede', 'mobilidade-de-tornozelo-na-parede', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Panturrilhas','Tibial anterior'], 'Mobilidade', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Dorsiflexão de tornozelo', 'dorsiflexao-de-tornozelo', 'Mobilidade', 'Mobilidade', 'Tibial anterior', array['Panturrilhas'], 'Mobilidade', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Circundução de tornozelo', 'circunducao-de-tornozelo', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Panturrilhas','Tibial anterior'], 'Mobilidade', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Alongamento de sóleo', 'alongamento-de-soleo', 'Alongamento', 'Alongamento', 'Panturrilhas', array['Tibial anterior'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Agachamento profundo sustentado', 'agachamento-profundo-sustentado', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Quadríceps','Glúteo máximo','Panturrilhas'], 'Mobilidade', 'Membros inferiores', 'Peso corporal', 'Intermediário', 'Mobilidade', 6, true, true),
  ('Alongamento de isquiotibiais em pé', 'alongamento-de-isquiotibiais-em-pe', 'Alongamento', 'Alongamento', 'Posterior de coxa', array['Panturrilhas'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de isquiotibiais sentado', 'alongamento-de-isquiotibiais-sentado', 'Alongamento', 'Alongamento', 'Posterior de coxa', array['Panturrilhas'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento unilateral de posterior', 'alongamento-unilateral-de-posterior', 'Alongamento', 'Alongamento', 'Posterior de coxa', array['Panturrilhas'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Good morning com amplitude leve', 'good-morning-com-amplitude-leve', 'Mobilidade', 'Mobilidade', 'Posterior de coxa', array['Eretores da espinha','Glúteo máximo'], 'Mobilidade', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Alongamento de quadríceps em pé', 'alongamento-de-quadriceps-em-pe', 'Alongamento', 'Alongamento', 'Quadríceps', array['Flexores do quadril'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de quadríceps deitado', 'alongamento-de-quadriceps-deitado', 'Alongamento', 'Alongamento', 'Quadríceps', array['Flexores do quadril'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Couch stretch', 'couch-stretch', 'Alongamento', 'Alongamento', 'Flexores do quadril', array['Quadríceps'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Intermediário', 'Alongamento', 6, true, true),
  ('Figure 4 stretch', 'figure-4-stretch', 'Alongamento', 'Alongamento', 'Glúteo máximo', array['Glúteo médio'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de glúteo deitado', 'alongamento-de-gluteo-deitado', 'Alongamento', 'Alongamento', 'Glúteo máximo', array['Glúteo médio'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento borboleta', 'alongamento-borboleta', 'Alongamento', 'Alongamento', 'Adutores', array[]::text[], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento lateral de adutores', 'alongamento-lateral-de-adutores', 'Alongamento', 'Alongamento', 'Adutores', array['Glúteo médio'], 'Alongamento', 'Membros inferiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Cossack hold', 'cossack-hold', 'Alongamento', 'Alongamento', 'Adutores', array['Glúteo máximo'], 'Alongamento', 'Membros inferiores', 'Peso corporal', 'Intermediário', 'Alongamento', 6, true, true),
  ('Alongamento peitoral na parede', 'alongamento-peitoral-na-parede', 'Alongamento', 'Alongamento', 'Peitoral maior', array['Peitoral menor','Deltoide anterior'], 'Alongamento', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de bíceps na parede', 'alongamento-de-biceps-na-parede', 'Alongamento', 'Alongamento', 'Bíceps braquial', array['Antebraços'], 'Alongamento', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de tríceps acima da cabeça', 'alongamento-de-triceps-acima-da-cabeca', 'Alongamento', 'Alongamento', 'Tríceps braquial', array['Latíssimo do dorso'], 'Alongamento', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de deltóide posterior', 'alongamento-de-deltoide-posterior', 'Alongamento', 'Alongamento', 'Deltoide posterior', array['Trapézio'], 'Alongamento', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de ombro cruzado', 'alongamento-de-ombro-cruzado', 'Alongamento', 'Alongamento', 'Deltoide posterior', array['Trapézio'], 'Alongamento', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Child''s pose', 'childs-pose', 'Alongamento', 'Alongamento', 'Latíssimo do dorso', array['Eretores da espinha'], 'Alongamento', 'Tronco', 'Peso corporal', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de latíssimo', 'alongamento-de-latissimo', 'Alongamento', 'Alongamento', 'Latíssimo do dorso', array['Tríceps braquial'], 'Alongamento', 'Tronco', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento lombar com joelhos ao peito', 'alongamento-lombar-com-joelhos-ao-peito', 'Alongamento', 'Alongamento', 'Eretores da espinha', array['Glúteo máximo'], 'Alongamento', 'Tronco', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Rotação lombar deitado', 'rotacao-lombar-deitado', 'Alongamento', 'Alongamento', 'Oblíquos', array['Eretores da espinha'], 'Alongamento', 'Tronco', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de flexores de punho', 'alongamento-de-flexores-de-punho', 'Alongamento', 'Alongamento', 'Antebraços', array[]::text[], 'Alongamento', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Alongamento de extensores de punho', 'alongamento-de-extensores-de-punho', 'Alongamento', 'Alongamento', 'Antebraços', array[]::text[], 'Alongamento', 'Membros superiores', 'Sem equipamento', 'Iniciante', 'Alongamento', 6, true, true),
  ('Mobilidade de punhos no chão', 'mobilidade-de-punhos-no-chao', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Antebraços'], 'Mobilidade', 'Membros superiores', 'Peso corporal', 'Iniciante', 'Mobilidade', 6, true, true),
  ('Saudação ao sol', 'saudacao-ao-sol', 'Mobilidade', 'Mobilidade', 'Corpo inteiro', array['Flexores do quadril','Posterior de coxa','Deltoide anterior'], 'Mobilidade', 'Corpo inteiro', 'Peso corporal', 'Intermediário', 'Mobilidade', 6, true, true),
  ('Inchworm', 'inchworm', 'Mobilidade', 'Mobilidade', 'Corpo inteiro', array['Posterior de coxa','Core','Deltoide anterior'], 'Locomover', 'Corpo inteiro', 'Peso corporal', 'Intermediário', 'Ativação', 6, true, true),
  ('Deep squat hold', 'deep-squat-hold', 'Mobilidade', 'Mobilidade', 'Mobilidade', array['Quadríceps','Glúteo máximo','Panturrilhas'], 'Mobilidade', 'Membros inferiores', 'Peso corporal', 'Intermediário', 'Mobilidade', 6, true, true),
  ('Bird dog', 'bird-dog', 'Mobilidade', 'Mobilidade', 'Core', array['Glúteo máximo','Deltoide posterior'], 'Estabilizar', 'Tronco', 'Peso corporal', 'Iniciante', 'Ativação', 6, true, true),
  ('Dead bug', 'dead-bug', 'Mobilidade', 'Mobilidade', 'Core', array['Reto abdominal','Flexores do quadril'], 'Estabilizar', 'Tronco', 'Peso corporal', 'Iniciante', 'Ativação', 6, true, true),
  ('Prancha com alcance', 'prancha-com-alcance', 'Mobilidade', 'Mobilidade', 'Core', array['Deltoide anterior','Oblíquos'], 'Estabilizar', 'Tronco', 'Peso corporal', 'Intermediário', 'Ativação', 6, true, true)
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  muscle_category = excluded.muscle_category,
  muscle_group_primary = excluded.muscle_group_primary,
  muscle_groups_secondary = excluded.muscle_groups_secondary,
  movement_type = excluded.movement_type,
  body_region = excluded.body_region,
  equipment = excluded.equipment,
  difficulty_level = excluded.difficulty_level,
  exercise_type = excluded.exercise_type,
  duration_limit_seconds = excluded.duration_limit_seconds,
  is_active = excluded.is_active,
  is_global = excluded.is_global;
