export type {
  AuthAccountStatus,
  AuthRole,
  AuthSession,
  ResolvedAuthSession,
  AuthUser,
  CompleteFirstAccessInput,
  ForgotPasswordInput,
  LoginInput,
  RegisterInput,
  ResetPasswordInput,
  TeacherPlanType,
  TeacherSubscriptionStatus,
  UpdateProfileInput,
} from "@/types/auth";
